[package]
name = "cement"
version = "2.2.2"
rust-version = "1.90"
edition = "2024"

[dependencies]
anyhow = { version = "1.0" }
clap = { version = "4.4", features = ["derive", "env"] }
futures-util = { version = "0.3" }
gpw = { version = "0.1" }
hyper-rustls = { version = "0.25", features = ["webpki-roots"] }
lazy_static = { version = "1.4" }
libsql = { version = "0.9", features = ["remote", "serde"] }
minijinja = { version = "2.16", features = ["loader"] }
poem = { version = "3.0", features = ["anyhow", "csrf", "static-files"] }
rand = { version = "0.10" }
serde = { version = "1.0", features = ["derive"] }
time = { version = "0.3", features = ["formatting", "serde"] }
tokio = { version = "1.32", features = ["full"] }
toml = { version = "1.0" }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[build-dependencies]
build-data = { version = "0.3" }
