CREATE TABLE IF NOT EXISTS posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slug TEXT NOT NULL,
  content TEXT NOT NULL,
  added TIMESTAMP NOT NULL,
  remote TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS posts_slugs_ix ON posts (slug);
